tracker and report fixes
walterdd/Auditory_tracking pull request #10
Opened 2017-02-27 12:23 UTC by iluhandric

* класс трекера, теперь вся функциональность, связанная с трекингом в нем
* скрипт экстракта стал чище
* изменил вычисление статистик 
* еще небольшие изменения

2017-03-07 18:37 UTC, walterdd commented on boremeter/tracker.py
> +        detected_faces = detect_faces(self.cur_frame, grey_scale=True)
Мне кажется, лучше вынести детекцию в extract_people, потому что так будет легче менять тип детекции. Передавать аргументом сетки, например

2017-03-07 19:05 UTC, walterdd reviewed
Посмотрела, добавила пару комментариев.
При запуске на 3-минутном видео с дефолтным frames_limit=20000 у меня все упало на 4343 фрейме с багом в трекере:
`File "build/bdist.linux-x86_64/egg/boremeter/tracker.py", line 27, in read_frame`
`cv2.error: /root/opencv/opencv/modules/imgproc/src/color.cpp:7564: error: (-215) scn == 3 || scn == 4 in function cvtColor`

Как будто пытается считаться еще один фрейм после того, как видео закончилось. Не нашла бага в коде. При маленьких frames_limit все норм

2017-03-07 19:05 UTC, walterdd commented on boremeter/gen_report.py
>      with temporary_directory() as tmp_dir:
функции visualize не надо передавать аргумент detection_step

2017-03-07 19:16 UTC, walterdd commented on boremeter/visualize.py
>      cur_frame_num = 0
Почему visualize так долго работает? :(
Если сделаешь for-цикл и tqdm я буду счастлива 🌹

2017-03-07 20:45 UTC, walterdd commented on boremeter/tracker.py
> +    def read_frame(self, frame):
Сюда хорошо бы добавить параметр gray, который повсюду есть. Для сеток детектора нужны 3 канала

2017-03-07 21:05 UTC, walterdd commented on boremeter/tracker.py
> +                    self.bboxes_by_id[old_id] = new_bbox.resize(0.8)
Что делает здесь resize?

2017-03-07 21:32 UTC, walterdd commented on boremeter/tracker.py
> +            points_number = self.bboxes_by_id[new_id].w / 2
Это же не целое число?

2017-03-07 22:30 UTC, walterdd commented on boremeter/extract_people.py
> +        if not has_more_frames:
Вот, в чем проблема. Проверка должна быть после `has_more_frames, cur_frame = input_video.read()`

2017-03-08 01:27 UTC, iluhandric commented on boremeter/tracker.py
> +    def read_frame(self, frame):
обязательно
и тут вроде так удобнее

2017-03-08 21:58 UTC, walterdd commented on boremeter/extract_people.py
> +        crop_faces(frame, tracker.cur_frame_num, new_bboxes_by_id, tmp_dir)
Надо передавать - `crop_faces(tracker.cur_frame, ...)`

Это вообще жуткий фейл, потому что интерес, пол и возраст оценивается по тому, что было на первом фрейме на месте bb

2017-03-17 14:45 UTC, walterdd requested changes

2017-03-17 14:45 UTC, walterdd commented on boremeter/tracker.py
> +                continue
Я не понимаю логики. В чем смысл генерить здесь точки для cur_id и переходить на следующую итерацию цикла для нового cur_id, не используя optical flow?

2017-03-18 08:45 UTC, walterdd commented on boremeter/tracker.py
> +    def read_frame(self, frame):
Окс

2017-03-18 08:45 UTC, iluhandric commented on boremeter/tracker.py
> +                    self.bboxes_by_id[old_id] = new_bbox.resize(0.8)
уменьшает рамку как ни странно
так вроде чуть лучше пашет

2017-03-18 08:46 UTC, iluhandric commented on boremeter/gen_report.py
>      with temporary_directory() as tmp_dir:
это правда

2017-03-18 08:46 UTC, iluhandric commented on boremeter/gen_report.py
>      with temporary_directory() as tmp_dir:
наверное

2017-03-18 08:48 UTC, iluhandric commented on boremeter/tracker.py
> +                continue
мы их сохранили и на следующем фрейме будем их трекать

2017-03-18 08:52 UTC, walterdd commented on boremeter/tracker.py
> +                continue
Ну вроде не было точек у тех id, которые не были найдены детектором и замачены на этом фрейме. Потенциально это шум. Если на следующем фрейме (или через таймаут фреймов) эти рамки будут задетекчены, то для них будут генерироваться точки в мачинге. Если они не будут задетекчены через таймаут фреймов, то зачем их вообще трекать?

2017-03-18 08:53 UTC, walterdd commented on boremeter/tracker.py
> +                continue
Просто я борюсь с шумом ⚔️

2017-03-20 06:34 UTC, walterdd approved these changes

2017-03-20 06:35 UTC, merged