Add mtcnn_detector and batch processing in recognition
walterdd/Auditory_tracking pull request #11
Opened 2017-03-21 09:07 UTC by walterdd

2017-04-28 13:58 UTC, lovevso requested changes

2017-04-28 13:58 UTC, lovevso commented on boremeter/bounding_boxes.py
> +    return BoundingBox(x, y, right - x, top - y)
точно top, а не bottom?

2017-04-28 13:58 UTC, lovevso commented on boremeter/mtcnn_detector.py
> +
файл - дичайшая дичь, ничего не понятно

2017-04-28 13:58 UTC, lovevso commented on boremeter/recognize_people.py
> +            detected_faces.loc[i, 'age'] = 25 # mean? median? maybe we should delete faces that appear on very few frames?
yeah, do it

2017-04-28 13:58 UTC, iluhandric commented on boremeter/tracker.py
> +    def __init__(self, caffe_models_path, timeout=100, detection_method='mtcnn'):
сделай отдельный класс для детектора, чтобы трекер принимал в конструктор объект детектора и никак не зависел от того, что у него там внутри, просто вызывая методы

2017-04-29 09:04 UTC, walterdd commented on boremeter/bounding_boxes.py
> +    return BoundingBox(x, y, right - x, top - y)
точно

2017-04-29 09:06 UTC, walterdd commented on boremeter/mtcnn_detector.py
> +
да, я каскад не писала сама, а взяла код с https://github.com/DuinoDu/mtcnn/blob/master/demo.py . Предлагаю пока оставить, как есть

2017-04-29 09:07 UTC, walterdd commented on boremeter/recognize_people.py
> +            detected_faces.loc[i, 'age'] = 25 # mean? median? maybe we should delete faces that appear on very few frames?
Не, я пробовала, не надо. Если большой шаг детекции, то много лиц пропадает

2017-04-29 09:14 UTC, walterdd commented on boremeter/tracker.py
> +    def __init__(self, caffe_models_path, timeout=100, detection_method='mtcnn'):
done

2017-05-02 10:35 UTC, lovevso approved these changes

2017-05-02 10:35 UTC, merged