Add setup.py
walterdd/Auditory_tracking pull request #5
Opened 2017-01-24 10:34 UTC by walterdd

2017-01-24 21:17 UTC, romovpa requested changes
Нужно исправить все, что я прокомменировал

2017-01-24 21:17 UTC, romovpa commented on setup.py
> +    url='https://github.com/walterdd/Auditory_tracking',
это случаем не старый `url`?

2017-01-24 21:17 UTC, romovpa commented on boremeter/__init__.py
> +from gen_report import *
`import *` — опасная операция, это не только засоряет namespace, но и еще может привести к печальным последствиям; 

Жизненные примеры: 
- автор `gen_report` не со зла добавил в свой модуль вспомогательную функцию `fast_extract` и перезатер `extract_people.fast_extract`
- автор `gen_report` не от большого ума добавил в свой модуль функцию `sum`, `map`, `str` или переменную `list`; бедняга, сделавший `from gen_report import *` будет очень долго удивляться неадекватному поведению своей программы

2017-01-24 21:17 UTC, romovpa commented on boremeter/__init__.py
> +from gen_report import *
В некоторых случаях, модуль библиотеки специально делается так, чтобы пользователь сделал `from matplotlib.pylab import *` и не запариваясь пользовался большим набором удобных функций в своем name space. В таком случае, в модуле, из которого делают `import *` обязательно добавляется служебная переменная `__all__`, которая говорит, что конкретно будет импортиться при `import *`, тем самым ограждая импорт от добавления в неймспейс пользователя нежелательных вспомогательных функций.

Такой паттерн можно увидеть в любом модуле [в sklearn-е](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/svm/__init__.py)

2017-01-24 21:17 UTC, romovpa commented on setup.py
> +)
Здесь не хватает поля с зависимостями `install_requires`.
Имеет смысл перенести зависимости в `setup.py`, а в `requirements.txt` написать:
```
-e .
```
это приведет к тому, что команда `pip install -r requirements.txt` будет подтягивать зависимости из `setup.py`

Подробнее [можно почитать здесь](https://caremad.io/posts/2013/07/setup-vs-requirement/)

2017-01-24 21:17 UTC, romovpa commented on Dockerfile
> +FROM boremeter/caffe-opencv
А где dockerfile для этого имейджа? ты его на коленке сделала?
Это мне просто интересно, здесь проблемы нет.

2017-01-24 21:17 UTC, romovpa commented on Dockerfile
>    pip install Jinja2 pandas tqdm
Здесь можно сделать просто `python setup.py install`, и это подтянет все необходимые зависимости (конечно, они должны быть прописаны в `setup.py`, об этом я написал).

2017-01-24 21:17 UTC, romovpa commented on Dockerfile
>    pip install Jinja2 pandas tqdm
Таким образом, когда у библиотеки появятся новые зависимости, их не нужно будет обновлять в куче мест — только в `setup.py`.

2017-01-24 21:17 UTC, romovpa commented on setup.py
> +    author='Ilya Soloviev, Artem Shaforostov, Daria Walter',
![](http://i1.kym-cdn.com/photos/images/newsfeed/000/082/456/Okay.png)

2017-01-24 21:17 UTC, romovpa commented on setup.py
> +    name='boremeter',
Меня немного диссонирует, когда название пишут то с большой буквы, то с маленькой. Это не принципиально, но было бы эстетичнее, если бы репозиторий назывался так же, с маленькой буквы.

2017-01-24 21:17 UTC, romovpa commented on boremeter/__init__.py
> +from gen_report import *
Исторически принято завершать файл с кодом символом конца строки.
[Вот здесь](http://stackoverflow.com/questions/5813311/no-newline-at-end-of-file) в ответах можно найти ответ почему. 
Git и GitHub поддерживают эту традицию. Если сделать `git diff`, то может появиться сообщение `No newline at the end of file`. Здесь в интерфейсе можно видеть красную стрелочку в конце файла, когда нет перевода строки в конце файла.

2017-01-24 21:17 UTC, romovpa commented on setup.py
> +)
Здесь тоже No newline at end of file

2017-01-24 21:17 UTC, romovpa commented on README.md
>  ### Without Docker
Мне не нравится структура повествования, какая-то она не последовательная.

Давай сделаем по аналогии [вот с этим](https://github.com/jupyterhub/jupyterhub):

- Technical overview (перечисление того, что может библиотека, какие в ней реализованы алгоритмы)
- Installation
  - Check prerequisites
  - Install package
  - Use `boremeter` from cmdline
- Using Docker (пример как сделать docker pull и выполнить команду из контейнера)

2017-01-24 21:21 UTC, romovpa commented
К пул реквесту неплохо писать описание: саммари по изменениям, на которые ревьюверу нужно обратить внимание.

2017-01-24 21:39 UTC, romovpa commented on README.md
> +--frames_limit  -  number of frames to process
Это пользователь и так может сделать через `boremeter --help`, главное сделать так, чтобы `--help` работал и был информативен.

2017-01-24 21:44 UTC, romovpa requested changes

2017-01-24 21:44 UTC, romovpa commented on README.md
> +--frames_limit  -  number of frames to process
Всегда нужно избегать дублирования информации, иначе при изменении придется менять в разных местах. Это как правило приводит к тому, что информация в разных местах расходится. 
Этот принцип называется [DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself), один из основополагающих в современном программировании.

2017-01-24 21:59 UTC, romovpa commented
![](https://github.trello.services/images/mini-trello-icon.png) [Docker контейнер](https://trello.com/c/PHtzcq3t/5-docker)

2017-01-25 13:18 UTC, walterdd commented on Dockerfile
> +FROM boremeter/caffe-opencv
dockerfile для boremeter/caffe-opencv лежит у меня локально, он подтягивает kaixhin/caffe с caffe и устанавливает opencv. Надо этот файл тоже выкладывать в репозиторий?

2017-01-25 13:19 UTC, walterdd commented on setup.py
> +    name='boremeter',
хорошо, мы же будем делать новый репозиторий

2017-01-25 13:20 UTC, walterdd commented on setup.py
> +    url='https://github.com/walterdd/Auditory_tracking',
верно

2017-01-25 13:20 UTC, walterdd commented on setup.py
> +)
done

2017-01-25 13:21 UTC, walterdd commented on boremeter/__init__.py
> +from gen_report import *
done

2017-01-25 15:19 UTC, romovpa commented on Dockerfile
> +FROM boremeter/caffe-opencv
Правильно здесь поступить так: сделай открытый репозиторий на гитхабе walterdd/docker-caffe-opencv, в котором находится Dockerfile и иные файлы для сборки образа, привяжи к нему walterdd/caffe-opencv на DockerHub, а в этом проекте просто используй

2017-01-25 16:11 UTC, walterdd commented on README.md
> +--frames_limit  -  number of frames to process
хорошо, --help выводит нечто разумное и так

2017-01-25 16:33 UTC, walterdd commented on Dockerfile
> +FROM boremeter/caffe-opencv
окей, сделаю

2017-01-25 17:35 UTC, romovpa requested changes
Придется еще немного поправить

2017-01-25 17:35 UTC, romovpa commented on README.md
> +[age.prototxt](https://data.vision.ee.ethz.ch/cvl/rrothe/imdb-wiki/static/age.prototxt)
Сделай этот список в виде буллетов:

```
- first
- second
- ...
```
а то как-то неестественно выглядит

2017-01-25 17:35 UTC, romovpa commented on README.md
>  [slides](https://docs.google.com/presentation/d/14mCydv-_sYkVHxImUnIX6PWRfpsfL49311rG099QPvc/edit#slide=id.g19ead2f26b_0_16)
slides -> Slides from presentation of our project (russian)

2017-01-25 17:35 UTC, romovpa commented on boremeter/__init__.py
> +from gen_report import main
Кстати, а нафига в корневом пакете `main`-функция? 
Я даже не могу себе представить, в каком случае ее пользователь захочет заимпортить.

2017-01-25 17:35 UTC, romovpa commented on boremeter/gen_report.py
> +    template = j2_env.get_template('/root/Auditory_tracking/boremeter/template.html')
Не, вот так нельзя делать. Затачиваться под одно единственное окружение (пусть даже это докер) — неправильно.

Кроме того, я вам на встрече рассказывал как правильно тут поступить: вместо `FileSystemLoader` воспользоваться `PackageLoader`, как [вот здесь](http://jinja.pocoo.org/docs/2.9/api/), и тогда `get_template('template.html')` будет искать файл там, где установлен наш пакет `boremeter` (где бы он при этом ни был установлен).

2017-01-25 17:35 UTC, romovpa commented on boremeter/gen_report.py
> +add_arg('--output_video',       default='NAN', type=str,            help='path to output .avi file with visualisation of bounding boxes')
🙏  ради Оккама, убери эту мусорную переменную add_arg
Сделай так, как рекомендует делать документация `argparse`: `parser.add_argument(...)`

2017-01-25 17:35 UTC, romovpa commented on README.md
>  <img src="https://github.com/walterdd/Auditory_tracking/blob/master/dogg.jpg" width="224">
Вот так старые ссылки и плодятся.

А все потому, что никогда, почти никогда не нужно использовать абсолютные пути. Везде где видите абсолютный путь, если он не к внешнему источнику — бойтесь. 

Здесь можно написать просто `<img src="dogg.jpg" width="224">`

2017-01-25 17:35 UTC, romovpa commented on setup.py
> +    author='Ilya Soloviev, Artem Shaforostov, Daria Walter',
Меня таки не будет в соавторах, да? 😿

2017-01-25 17:37 UTC, walterdd commented on setup.py
> +    author='Ilya Soloviev, Artem Shaforostov, Daria Walter',
(: я долго думала, что ты имел в виду
мда, некрасиво получается

2017-01-25 17:43 UTC, walterdd commented on README.md
>  <img src="https://github.com/walterdd/Auditory_tracking/blob/master/dogg.jpg" width="224">
о, интересно, а как она вообще подгружалась?

2017-01-25 17:49 UTC, romovpa requested changes

2017-01-25 17:49 UTC, romovpa commented on README.md
> +## Boremeter
Тут можно сделать Header-1

```
# Boremeter
```

или 

```
Boremeter
---------
```

2017-01-25 17:50 UTC, walterdd commented on boremeter/__init__.py
> +from gen_report import main
потому что это функция, которая запускается в 
if __name__ == "__main__"  :) 

Да, но ее правда можно не импортировать, потому что она прописана в entry_points в setup

2017-01-25 18:26 UTC, romovpa approved these changes

2017-01-25 18:26 UTC, romovpa commented
🌹 
можно мержить

2017-01-25 18:31 UTC, merged