Fixes
walterdd/Auditory_tracking pull request #6
Opened 2017-01-25 19:07 UTC by walterdd

fixed paths to templates folder
fixed bugs in gen_report

2017-01-25 19:12 UTC, romovpa requested changes

2017-01-25 19:12 UTC, romovpa commented on setup.py
> +)
newline

И еще, кажется нужно добавить `package_data`. Иначе при `pip install` / `python setup.py install` не установятся классификаторы хаара и шаблон.

2017-01-25 22:33 UTC, romovpa requested changes

2017-01-25 22:33 UTC, romovpa commented on boremeter/gen_report.py
> +    shutil.rmtree("tmp")
а зачем для этого отдельная функция?

2017-01-25 22:33 UTC, romovpa commented on boremeter/gen_report.py
> +    os.mkdir("tmp")
Так лучше не делать. Мало ли зачем пользователю нужен каталог `tmp`, может там что-то важное, а ты его удалять.

Для создания временного каталога есть [`tempfile.mkdtemp`](https://docs.python.org/2/library/tempfile.html#tempfile.mkdtemp)

2017-01-25 22:33 UTC, romovpa commented on boremeter/gen_report.py
>  args = parser.parse_args()
Кстати, крайне странно, что parser.parse_args() находится не в `main()`, а в модуле. Это означает, что при попытке заимпортить этот модуль будут парситься аргументы. Вот будет удивление, ты `from boremeter.gen_report import main`, а оно тебе "у тебя неправильно заданы аргументы."

Все, начиная от `parser = argparse.ArgumentParser()` нужно в `main()`

2017-01-25 22:33 UTC, romovpa commented on boremeter/gen_report.py
> +                                                                                         'visualisation of bounding boxes')
Здесь можно без бекслеша (`\`) обойтись, т.к. внутри скобок. И вообще, лучше убрать эти дурацкие пробелы между аргументами.

2017-01-25 22:33 UTC, romovpa commented on boremeter/gen_report.py
> +                                                                                         'visualisation of bounding boxes')
Правильнее здесь сделать `default=None`. Зачем придумывать специальную строку, когда есть `None`?

2017-01-25 22:33 UTC, romovpa commented on boremeter/gen_report.py
>  def array_to_string(arr):
`str(arr)` не?

2017-01-25 22:33 UTC, romovpa commented on boremeter/gen_report.py
>  def array_to_string(arr):
можно еще попробовать `repr(arr)`, если не устроит `str(arr)`

2017-01-25 22:33 UTC, romovpa commented on boremeter/gen_report.py
> +        sys.exit()
`validate_input_path` и `validate_output_path` можно было слить в одну функцию, добавив дополнительные аргументы

2017-01-25 22:33 UTC, romovpa commented on boremeter/gen_report.py
> +    validate_output_path(args.output_csv)
`argparse` — это [довольно функциональный](https://mkaz.tech/code/python-argparse-cookbook.html) фреймворк для того, чтобы отпарсить и провалидировать аргументы командной строки, он создан для того, чтобы разработчик по выполнению `args = parser.parse_args()` получил абсолютно правильный и готовый к работе `args`, городить рядом дополнительные проверки — это значит плодить дополнительные сущности. 

Для входного файла можно использовать `argparse.FileType`, и не проверять наличие, а просто сказать `required=True` при создании аргумента.

Если очень хочется ограничить `frames_limit`, то лучше сделать как-то [вот так](http://stackoverflow.com/questions/18700634/python-argparse-integer-condition-12).
Похожее можно сделать и для выходного, но зачем? Пользователь и так поймает довольно информативное исключение о том что директории не существует, либо не хватает прав на запись. Мне валидировать все и писать везде сообщения — это излишний перфекционизм.

2017-01-25 22:33 UTC, romovpa commented on boremeter/gen_report.py
> +    os.environ["caffe_models"] = args.caffe_models_path
Переменные окружения обычно читают, но не пишут. Программа, изменяющая переменную окружения делает это только на время своей работы, и это довольно странная операция, лучше ее вообще не делать.

Вместо этого, в том месте где нужно получить путь к моделям, нужно написать как-то так:
```python
caffe_models_path = args.caffe_models_path or os.environ.get('CAFFE_MODELS_PATH') or DEFAULT_CAFFE_MODELS_PATH
```

И еще, переменные окружения по стандарту unix пишутся большими буквами: `CAFFE_MODELS_PATH`

2017-01-25 22:33 UTC, romovpa commented on boremeter/gen_report.py
> +    setup(args)
Я не вижу никакого смысла здесь выделять в отдельную функцию содержимое `setup()` и `farewell()`.
Если хочется выделить эти различные по смыслу части, то это лучше сделать пробелами в коде и комментариями.

2017-01-25 22:33 UTC, romovpa commented on boremeter/gen_report.py
>      print ("Extracting statistics.....")
Зачем вот эта копипаста выше?
Можно же написать вот так:
```python
detect.fast_extract(args.file, visualize=(args.output_video != 'NAN'), frames_limit=args.frames_limit, output_file_name=args.output_video)
```

Про `"NAN"` я уже писал выше, здесь нужно просто `None` использовать и не выносить нормальным людям мозг. 

Неужели аргумент `output_file_name` принимает видео? А нельзя было его как-нибудь получше назвать?

Как-то значение, передаваемое `visualize` коррелирует с `output_file_name`. Может быть один из них не нужен? `visualize = args.output_video is not None`?

2017-01-25 22:33 UTC, romovpa commented on boremeter/gen_report.py
> +    stats = rec.get_stats(table=args.output_csv)
Я бы не обратил внимание, если бы функция `get_*` не принимала бы на вход `output`. Это как "бери давай". 

Здесь можно было получить от объекта-распознавателя статистику в виде pandas-таблицы или еще чего, а затем здесь же (в `main()`) сохранить ее в CSV, здесь же передать эту переменную функции `get_HTML`  на дальнейшее растерзание.

2017-01-25 22:33 UTC, romovpa commented on boremeter/gen_report.py
>      gen_HTML(args.output_html, stats[0], stats[1], stats[2], stats[3])
`stats[0], stats[1], stats[2], stats[3]`
вот за это можно оторвать руки

Потому что stats — это не tuple, и обращаться с ним принято вот так:
```
alice, bob, carol, smth_else = rec.get_stats(...)
```

2017-01-27 11:00 UTC, walterdd commented on boremeter/gen_report.py
> +    validate_output_path(args.output_csv)
output пути, мне кажется, надо валидировать затем, что пользователь поймает исключение только после того, как программа отработает почти целиком, а это может быть долго, будет обидно.
Но вроде бы `type=argparse.FileType('w')` достаточная валидация

2017-01-27 11:02 UTC, walterdd commented on boremeter/gen_report.py
> +    os.environ["caffe_models"] = args.caffe_models_path
Хорошо, а зачем нужена константа DEFAULT_CAFFE_MODELS_PATH?
Я присваиваю дефолтное значение в args.caffe_models_path

2017-01-27 11:02 UTC, walterdd commented on boremeter/gen_report.py
> +    shutil.rmtree("tmp")
да, незачем

2017-01-27 11:06 UTC, romovpa requested changes

2017-01-27 11:06 UTC, romovpa commented on boremeter/extract_people.py
>                          img[bb[1] : bb[1] + bb[3], bb[0] : bb[0] + bb[2]])
Здесь тоже было бы здорово использовать `os.path.join()`

2017-01-27 11:06 UTC, romovpa commented on boremeter/extract_people.py
>                      img[bb[1] : bb[1] + bb[3], bb[0] : bb[0] + bb[2]])
И здесь `os.path.join()`

2017-01-27 11:06 UTC, romovpa commented on boremeter/extract_people.py
>      return
`return` можно не делать
когда код функции закончится, она и так завершится и вернет `None`

2017-01-27 11:06 UTC, romovpa commented on boremeter/extract_people.py
>      return
да тут масса этих ненужных return-ов!

2017-01-27 11:06 UTC, romovpa commented on boremeter/gen_report.py
> +                            tmp_dir=tmp_dir, detection_step=DETECTION_STEP, output_videofile=args.output_video)
Почему бы не сделать `with temporary_directory() as tmp_dir:` внутри `fast_extract`? Функции не придется передавать лишний аргумент, и вообще, зачем пользователю функции `fast_extract` знать, что там внутри создается временная папка? Ну и код `main()` будет проще.

2017-01-27 11:06 UTC, romovpa commented on boremeter/recognize_people.py
> +    detected_faces = detected_faces.fillna('nan')
не понимаю, зачем это здесь делается

Есть специальное значение `np.nan`, оно же `float('nan')`
нет необходимости числовые колонки заполнять строковыми значениями, они при этом еще и преобразуются из числового типа в `object`, что негативно сказывается на всем

[Подробнее про пропущенные значения в numpy/pandas](http://pandas.pydata.org/pandas-docs/stable/missing_data.html)

2017-01-27 11:13 UTC, walterdd commented on boremeter/gen_report.py
> +                            tmp_dir=tmp_dir, detection_step=DETECTION_STEP, output_videofile=args.output_video)
Так не получится - `recognize_people` также принимает `tmp_dir`, считывает оттуда изображения

2017-01-27 11:15 UTC, romovpa commented on boremeter/gen_report.py
> +    validate_output_path(args.output_csv)
Ок.
> Но вроде бы type=argparse.FileType('w') достаточная валидация
Но учитывай, что при этом `FileType('w')` сразу открывает файл для записи, и нужно работать с ним как с файлом-объектом

2017-01-27 11:16 UTC, romovpa commented on boremeter/gen_report.py
> +                            tmp_dir=tmp_dir, detection_step=DETECTION_STEP, output_videofile=args.output_video)
а, точно
в diff-е просто не видно, что там на самом деле несколько функций используют tmp_dir

2017-01-27 11:17 UTC, romovpa commented on boremeter/gen_report.py
> +    os.environ["caffe_models"] = args.caffe_models_path
> Я присваиваю дефолтное значение в args.caffe_models_path
Если гарантируется, что в `args.caffe_models_path` будет значение, то тогда незачем. Я привел пример без учета ситуации.

2017-01-27 11:20 UTC, romovpa approved these changes

2017-01-27 11:36 UTC, merged