refactor
walterdd/Auditory_tracking pull request #7
Opened 2017-01-28 05:31 UTC by iluhandric

1) Теперь есть класс для bounding box
2) Визуализация после всей обработки, теперь на видео отображаются данные о человеке
3) Возраст человека - средний возраст по всем обработанным фреймам с ним
4) С полом то же самое
5) Почистил код
6) PEP8

2017-01-28 07:03 UTC, romovpa commented
Такие большие изменения одним коммитом не делаются.
Пулл реквест лучше разбивать на последовательность мелких, но понятных изменений.

2017-01-28 12:13 UTC, romovpa requested changes
Код стал значительно лучше, чем то что было раньше. Я был приятно удивлен. Но, есть куча вещей, которые предстоит учесть.

2017-01-28 12:13 UTC, romovpa commented on boremeter/bbs.py
> +class Bb:
Такое название класса не годится совсем. Думаю ты не разоришься на носителях, если переименуешь его в `BoundingBox`. 
Кстати, в PyCharm есть автоматическое переименование Refactor > Rename, которое ищет все использования идентификатора и правильно все меняет.

2017-01-28 12:13 UTC, romovpa commented on boremeter/bbs.py
> +    def __init__(self, x=0, y=0, w=0, h=0, as_tuple=None):
Ты точно хочешь, чтобы этот класс был таким сложным? Чем меньше сущностей, тем проще читать, использовать код, тем меньше вероятность что ты поменяешь в одном месте, а в другом поломается.

2017-01-28 12:13 UTC, romovpa commented on boremeter/bbs.py
> +    def __init__(self, x=0, y=0, w=0, h=0, as_tuple=None):
Какой смысл давай аргументам `__init__` значения по-умолчанию? Приведи пример, когда это может быть удобно и понятно.

2017-01-28 12:13 UTC, romovpa commented on boremeter/bbs.py
> +    def __init__(self, x=0, y=0, w=0, h=0, as_tuple=None):
`as_tuple` не нужен, в питоне для этого есть операция `*`:
```python
t = (x, y, w, h)
BoundingBox(*t)
```
Это если сильно хочется так сделать. Но на самом деле, мне трудно себе представить ситуацию, когда лучше так делать.

2017-01-28 12:13 UTC, romovpa commented on boremeter/bbs.py
> +    def __init__(self, x=0, y=0, w=0, h=0, as_tuple=None):
Нужно ли два набора параметров, взаимно однозначно соответствующих друг другу: (x, y, w, h) и (left, right, top, bottom)? Я бы оставил только один из них. Если сильно хочется, то можно для производных сделать свойство:

```python
@property
def right(self):
   return self.x + self.w
```

и тогда можно использовать просто вот так: `bbox.right`

2017-01-28 12:13 UTC, romovpa commented on boremeter/bbs.py
> +        return self.x, self.y, self.w, self.h
но зачем этот метод?

2017-01-28 12:13 UTC, romovpa commented on boremeter/bbs.py
> +        self.init_borders()
А вот если бы состояние класса описывалось одним набором параметров, то этот метод не нужен
Пользователь мог бы сделать просто и понятно:
```python
bbox.x += 10
```

Хотя, лучше использовать stateless классы (которые создаются и затем не меняют свое состояние). Эта концепция пришла из функционального программирования, снижает число ошибок и повышает понятность кода. В питоне есть генератор stateless-классов, код класса BoundingBox мог бы выглядеть вот так:
```python
import collections
BoundingBox = collections.namedtuple('x, y, w, h')
```

Но, к сожалению, в namedtuple нельзя добавить удобные функции.

2017-01-28 12:13 UTC, romovpa commented on boremeter/bbs.py
> +"""
Этот комментарий можно убрать под строчку `class BoundingBox:`
В таком случае он будет показываться, если сделать `help(BoundingBox)`

2017-01-28 12:13 UTC, romovpa commented on boremeter/bbs.py
> +class Bb:
Сам модуль тоже не грех назвать `bounding_boxes`

2017-01-28 12:13 UTC, romovpa commented on boremeter/detector.py
> +from bbs import *
Не нужно в коде библиотеки делать `import *`.
Я об этом [развернуто писал в ревью к Дашиному PR](https://github.com/walterdd/Boremeter/pull/5#discussion_r97645517).

2017-01-28 12:13 UTC, romovpa commented on boremeter/detector.py
> +        bbs.append(Bb(as_tuple=face))
Здесь логично использовать list comprehension:
```python
bbs = [Bb(as_tuple=face) for face in detected]
```

2017-01-28 12:13 UTC, romovpa commented on boremeter/detector.py
> +        bbs.append(Bb(as_tuple=face))
`bbs` — оч дурацкая аббревиатура, сторонний человек с ходу не поймет, что она означает.
С другой стороны, делать длинные но говорящие имена для локальных переменных — это тоже бессмысленно. 

`bboxes` в данном случае выглядит лучше: `bbox` — часто используемое сокращение для bounding box, ну и по слову `box` можно догадаться о чем идет речь.

2017-01-28 12:13 UTC, romovpa commented on boremeter/detector.py
> +    pass
Для чего здесь `pass`?

Если какой-то участок кода не дописан до конца, то логично оставить комментарий специального вида:
```python
# TODO: Implement this
```
такие комменты специальным образом подсвечиваются PyCharm-ом и на них обращает внимание pylint.

Есть функция не реализована настолько, что не может использоваться в коде (разработчик просто запланировал, что такая функция/метод будут в коде в будущем), то в тело функции вставляют:
```python
raise NotImplementedError()
```

2017-01-28 12:13 UTC, romovpa commented on boremeter/detector.py
>      if raw_detector == 'VJ':
А если не `"VJ"`, то что произойдет?

2017-01-28 12:13 UTC, romovpa commented on boremeter/extract_people.py
> +from bbs import *
[PEP8 "Imports"](https://www.python.org/dev/peps/pep-0008/#imports)

Imports should be grouped in the following order:

1. standard library imports
2. related third party imports
3. local application/library specific imports

You should put a blank line between each group of imports.

Этот стиль с одной стороны позволяет видеть, от чего зависит модуль, и насколько эти зависимости стандартные / библиотечные или локальные. С другой стороны, в таком порядке есть важная логика, в случае если ты или автор какой-то другой библиотеки при инициализации import-а меняет состояние интерпретатора, перезаписывает какие-нибудь переменные окружения.

2017-01-28 12:13 UTC, romovpa commented on boremeter/extract_people.py
> +from bbs import *
К такому оформлению импортов нужно привести во всех модулях.

2017-01-28 12:13 UTC, romovpa commented on boremeter/extract_people.py
>  from detector import *
Не делать `import *`.

2017-01-28 12:13 UTC, romovpa commented on boremeter/extract_people.py
>  from detector import *
Из соседнего модуля лучше сделать relative import:
```python
from .detector import *
```
явно указывая на то, что это соседний модуль, а не сторонний библиотечный

2017-01-28 12:13 UTC, romovpa commented on boremeter/extract_people.py
> +        bb = bbs[person_id]
```python
    for person_id in bbs:
        bb = bbs[person_id]
```
шта?

как это работает?

2017-01-28 12:13 UTC, romovpa commented on boremeter/extract_people.py
> +                    img[bb.top: bb.bottom, bb.left: bb.right])
Здесь для того чтобы уменьшить мешанину, можно разделить строчку по действиям:
```python
crop_file_path = os.path.join(tmp_dir, "frame%dperson%d.jpg" % (frame_num, person_id))
crop_img = img[bb.top: bb.bottom, bb.left: bb.right]
cv2.imwrite(crop_file_path, crop_img)
```
Такой код гораздо проще читать, в нем почти английским языком написано, что происходит

2017-01-28 12:13 UTC, romovpa commented on boremeter/extract_people.py
> +            ret, frame = input_video.read()
Переменная `ret` названа так, что у стороннего читателя вызывает много вопросов — что происходит?
Я не знаю, какой у нее смысл, и поэтому даже не могу предположить как работает этот код. 

Если `input_video.read()` возвращает кроме фрейма что-то вроде индикатора конца видео, то лучше так переменную и назвать:
```python
is_last_frame, frame = input_video.read()
end_of_video, frame = input_video.read()
```

2017-01-28 12:13 UTC, romovpa commented on boremeter/extract_people.py
>              cur_faces.pop(d, None)
1) зачем `.pop()` передавать второй агрумент, когда он и так по дефолту `None`, и тем более ты не ожидаешь от `pop` никакого результата?
2) в питоне есть вот такая конструкция: `del cur_faces[d]`, она имеено для этого предназначена, правильно использовать ее

2017-01-28 12:13 UTC, romovpa commented on boremeter/extract_people.py
>          for tmp in tmp_faces:
Не экономь на буквах, `for tmp_face in tmp_faces:`

2017-01-28 12:13 UTC, romovpa commented on boremeter/extract_people.py
>              cur_faces[tmp] = tmp_faces[tmp]
Твой код меня запутал. 
Я не понимаю, где хранятся индексы объектов `face`, а где сами объекты `face`.
А все потому что называть переменные надо правильно, если список содержит не объекты, а индексы объектов, то правильно его так и назвать: `tmp_face_indices`, если идентификаторы: `tmp_face_ids`

2017-01-28 12:13 UTC, romovpa commented on boremeter/extract_people.py
> +            writer.writerow([cur_frame_num, person_id, x, y, w, h])
Почему бы не написать так:
```python
face = cur_faces[person_id]
writer.writerow([
    cur_frame_num,
    person_id,
    face.x,
    face.y,
    face.w,
    face.h,
])
```

2017-01-28 12:13 UTC, romovpa commented on boremeter/extract_people.py
> +            writer.writerow([cur_frame_num, person_id, x, y, w, h])
не нужен этот `get()`

2017-01-28 12:13 UTC, romovpa commented on boremeter/gen_report.py
>  import extract_people as detect
Так extract или detect, что делается в том модуле, ёпта? 
Придется хотя бы определиться и не плодить разные названия одним и тем же сущностям.

2017-01-28 12:13 UTC, romovpa commented on boremeter/gen_report.py
>  import recognize_people as rec
Делать `import smth as x` позволительно только для библиотек, которые настолько часто используются в предметной области, что стали стандартом. Можно сделать `import numpy as np`, и именно так, и никак не `import numpy as npy`, потому как в сообществе принято импортить именно как `np`, в документации к `numpy` об этом есть целая рекомендация и все грамотные люди об этом знают.

Делая `import a as b` ты только лишь вводишь в заблуждение того, кому придется работать с кодом, и себя в том числе, затрудняя ему понимание что есть что. Нельзя так делать ради экономии байтов. Если тебе не нравится название `extract_people`, переименуй весь модуль и используй везде иное название.

2017-01-28 12:13 UTC, romovpa commented on boremeter/gen_report.py
> +RECOGNITION_STEP = DETECTION_STEP * 6
Константы действительно следует размещать именно в этом месте. 

Мне кажется стоит добавить возможность изменять эти значения в CLI.

2017-01-28 12:13 UTC, romovpa commented on boremeter/gen_report.py
>          autoescape=select_autoescape(['html'])
Когда пишешь по одному агрументу на строчку, после последнего нужно оставлять запятую.
Эта запятая ни на что не влияет и синтаксисом разрешена.

Зато, если другой разработчик решит добавить или поменять местами аргументы, то может получиться вот такая ошибка: 
```python
# before
the_function(
    (first_arg + 1),
    second_arg
)

# after
the_function(
    second_arg
    (first_arg + 1),
    third_arg
)
```
Здесь продолбалась запятая после `second_arg`, но интерпретатор тебе скажет не что запятой не хватает, а что `second_arg` не функция и не может быть вызвана. И дай бог, чтобы это действительно была не функция.

2017-01-28 12:13 UTC, romovpa commented on boremeter/gen_report.py
>      with open(filename, "wb") as fh:
Нам следует определиться с тем, какие кавычки мы будет использовать всегда, и использовать именно одинарные кавычки.

2017-01-28 12:13 UTC, romovpa commented on boremeter/gen_report.py
>              attention_arr=str(attention_arr.tolist())))
я бы тут разделил на 
```python
html = template.render()
report_file.write(html)
```

Ну и заменил бы плохое непонятное название `fh` на что-нибудь содержательное вроде `output_file`.

2017-01-28 12:13 UTC, romovpa commented on boremeter/gen_report.py
>          shutil.rmtree(d)
Эту функцию, вместе с `contextlib` было бы неплохо унести в отдельный модуль `boremeter.util`.
Для того чтобы не отвлекала от главной сути этого модуля, а еще такая функция может понадобиться где угодно в коде, и ее можно будет не реализовывать несколько раз.

2017-01-28 12:13 UTC, romovpa commented on boremeter/gen_report.py
>  from jinja2 import Environment, PackageLoader, select_autoescape
Давай переименуем `gen_report` в `cli`. Потому как основная задача этого модуля — обеспечить пользователю консольный интерфейс, который запускает пайплайн от начала до конца. А генерация отчета — это всего лишь одно из действий, которое делается в процессе пайплайна. 

Может быть, когда `gen_report` разрастется и станет сложным, его придется выделить в отдельный модуль (сейчас я не вижу в этом большого смысла).

2017-01-28 12:13 UTC, romovpa commented on boremeter/gen_report.py
> +                        '"age.caffemodel", "gender.caffemodel"')
Можно такие подробности здесь не писать. 
Просто "path to directory with pre-trained Caffe models".

Представь у тебя поменяются названия этих файлов, или добавятся новые. Ты не сможешь уследить за тем, чтобы во всех местах этот список файлов поменялся. А отсутствие информации сильно лучше ложной информации.

2017-01-28 12:13 UTC, romovpa commented on boremeter/recognize_people.py
>      del gender_net
Такие вещи в коде выглядят возмутительно.
Лучше оставить комментарий, почему и зачем это действие делается.
Например: удаляем `gender_net`, т.к. он уже не нужен и занимает много места в памяти.
Кстати говоря, чтобы по факту освободить память, этого удаления не достаточно, нужно сделать что-то вроде `import gc; gc.collect()`

2017-01-28 12:13 UTC, romovpa commented on boremeter/recognize_people.py
Этот модуль сильно комментировать не буду. 

Скажу только, что я бы выполнил распознавалку лиц в виде класса `FaceRecognizer`. Класс при инициализации загружает в свое локальное пространство всякие модели и живет с ними, вызовом методов объекта можно использовать модели и делать разные предсказания. 

С одной стороны, архитектура будет более понятной. С другой стороны, распознавание лиц таким образом становится переиспользуемым, его можно импортнуть и использовать для других задач.

2017-01-28 12:13 UTC, romovpa commented on boremeter/recognize_people.py
> +                                           ages[detected_faces['person_id'][i]][1]
Никогда не делай бэкслеш (`\`).

Бэкслеш можно не ставить внутри скобок. И если у тебя не влезает строчка, то просто оберни выражение в скобки и можно делать перенос.
```python
detected_faces.loc[i, 'age'] = (
    ages[detected_faces['person_id'][i]][0] /
    ages[detected_faces['person_id'][i]][1]
)
```

2017-01-28 12:13 UTC, romovpa commented on boremeter/recognize_people.py
> +                                           ages[detected_faces['person_id'][i]][1]
Следующая проблема: взятие индексов 0 и 1 — это непонятная операция.
Лучше развернуть это вот так:
```python
x, y = ages[detected_faces['person_id'][i]]
detected_faces.loc[i, 'age'] = x / y
```

При этом `x` и `y` назвать содержательно (я просто не знаю, что они означают).

Во многих местах этого модуля можно таким образом сильно упростить код.

2017-01-28 12:13 UTC, romovpa commented on boremeter/recognize_people.py
> +            detected_faces.loc[i, 'age'] = -1
Что еще за возраст -1? Ребенок за 3 месяца до зачятия? Что за бред?

Есть np.nan, None.

2017-01-28 12:55 UTC, iluhandric commented on boremeter/bbs.py
> +class Bb:
В остальных местах можно оставить bb?

2017-01-28 13:38 UTC, iluhandric commented on boremeter/bbs.py
> +        return self.x, self.y, self.w, self.h
чтобы не писать  bb.x, bb.y, bb.w, bb.h

2017-01-28 13:47 UTC, iluhandric commented on boremeter/bbs.py
> +        self.init_borders()
то есть я не делаю stateless?

2017-01-28 13:59 UTC, iluhandric commented on boremeter/detector.py
>      if raw_detector == 'VJ':
ничего хорошего)
это для того, чтобы, если мы будем юзать другие детекторы, можно было в параметры передавать их

2017-01-28 14:20 UTC, iluhandric commented on boremeter/extract_people.py
> +        bb = bbs[person_id]
bbs - словарь, в котором по id находятся рамки
это итерация по ключам

2017-01-28 14:41 UTC, iluhandric commented on boremeter/gen_report.py
>  from jinja2 import Environment, PackageLoader, select_autoescape
Давай потом с Дашей переименуем, просто этот файл в entry points на гите, и если его переименовывать локально, все ломается, когда пытаешься сбилдить докер и запустить

2017-01-28 14:57 UTC, iluhandric commented on boremeter/recognize_people.py
загруженная модель жрет очень много оперативы
поэтому я их даже удаляю

2017-01-28 19:45 UTC, romovpa commented on boremeter/bbs.py
> +class Bb:
bb — это как x или k. Если впервые видишь, то хуй поймешь что означает. Локальные переменные нужно все называть понятно.

2017-01-28 19:47 UTC, romovpa commented on boremeter/detector.py
>      if raw_detector == 'VJ':
Ну, тогда надо хотя бы исключение кинуть, если значение неправильное. Программа всегда должна работать хорошо или падать с исключением

2017-01-28 19:50 UTC, romovpa commented on boremeter/extract_people.py
> +        bb = bbs[person_id]
Словарь можно назвать так чтобы было понятно, что это словарь. Например: bbox_by_id.
А bbs — это bulletin board system.

2017-01-28 19:53 UTC, romovpa commented on boremeter/gen_report.py
>  from jinja2 import Environment, PackageLoader, select_autoescape
Нужно всего лишь в pycharme переименовать через Refactor. Все поменяется, в том числе в setup.py. А entry point станет указывать на модуль в его новом названии. 

Не бойся ломать. Мы рефакторим или где?

2017-01-28 19:56 UTC, romovpa commented on boremeter/recognize_people.py
Тем более. Все будет в объекте, ты будешь знать что жрет память именно этот объект и по надобности его удалять.

2017-01-29 13:14 UTC, romovpa requested changes
Еще прокомментировал

2017-01-29 13:14 UTC, romovpa commented on boremeter/bounding_boxes.py
> +    # check if two bounding boxes are close and have similar shapes
Лучше здесь сделать docstring:
```python
def are_close():
   '''Check if two ...'''
   if abs ...
```

2017-01-29 13:14 UTC, romovpa commented on boremeter/bounding_boxes.py
> +        return self.x + self.w / 2, self.y + self.h / 2
Предыдущие два геттера можно тоже в виде property выполнить.

Метод `get_*` делают, когда за подготовкой результатов этого метода стоит довольно сложная процедура, возможно даже параметризованная.

2017-01-29 13:14 UTC, romovpa commented on boremeter/bounding_boxes.py
> +            (abs(bb1.get_center()[1] - bb2.get_center()[1]) < bb1.h / 2))
Еще раз повторяю. Никогда не используй индексы у туплов.

```python
center1_x, center1_y = bb1.center
center2_x, center2_y = bb2.center
return (abs(center1_x - center1_y) < bb1.w / 2) and (abs(center1_y - center2_y) < bb1.h / 2)
```

2017-01-29 13:14 UTC, romovpa commented on boremeter/bounding_boxes.py
> +def are_close(bb1, bb2):
Язык не типизированный, поэтому нужно делать так, чтобы из названия было понятно, к чему применяется функция.

как вариант, можно назвать `bboxes_are_close`
еще можно выполнить это в виде метода `bbox.close_to(other_bbox)`

2017-01-29 13:14 UTC, romovpa commented on boremeter/bounding_boxes.py
> +    # check if two bounding boxes have an intersection
Тоже docstring, и в остальных функциях

2017-01-29 13:14 UTC, romovpa commented on boremeter/detector.py
>  def detect_faces(img, raw_detector='VJ'):
Фцнкция с неадекватным поведением при изменении параметра `raw_detector`.

2017-01-29 13:14 UTC, romovpa commented on boremeter/extract_people.py
> +from bounding_boxes import have_intersection, are_close
relative import

2017-01-29 13:14 UTC, romovpa commented on boremeter/__init__.py
>  from recognize_people import recognize_people
relative import

2017-01-29 13:14 UTC, romovpa commented on boremeter/extract_people.py
> +        crop_img = img[bbox.top: bbox.bottom, bbox.left: bbox.right]
пробел после двоеточия не нужен

2017-01-29 13:14 UTC, romovpa commented on boremeter/extract_people.py
> +        bbox = bboxes[person_id]
```python 
for person_id, bbox in bboxes.iteritems():
```

2017-01-29 13:14 UTC, romovpa commented on boremeter/extract_people.py
> +        bbox.resize(scale=1.3)
Лучше бы `BoundingBox` был stateless классом, а метод resize возвращал бы новый объект, а не изменял поля старого. Тогда не нужно было бы делать copy()

2017-01-29 13:14 UTC, romovpa commented on boremeter/extract_people.py
>      writer.writerow(['frame', 'person_id', 'x', 'y', 'w', 'h'])
А зачем здесь пишется сразу в csv-файл? Может лучше создать в памяти pandas-табличку и вернуть ее?
Нет необходимости во временном файле и операциях по форматированию этого файла (csv.writer).
Если пользователь в результате получает pandas-таблицу, то он может ее сохранить куда ему нужно, вызвав `df.to_csv`, или даже `df.to_excel`, как удобно. Пользователь может сразу по таблице что-то посчитать, построить график и т.д.

2017-01-29 13:14 UTC, romovpa commented on boremeter/extract_people.py
> +        cur_faces = {}  # bboxes by ids
Комментариями не отделаешься. Редко кто читает код как художественную литературу от начала до конца. Нужно писать так, чтобы посмотрев в небольшой кусок кода, человек все понял. 

Здесь, в принципе, можно все содержимое функции назвать небольшим куском кода, и тот кто будет читать скорее всего найдет комментарий. Но все равно, почему бы не назвать `cur_face_by_person`, `cur_bboxes_by_id`?

2017-01-29 13:14 UTC, romovpa commented on boremeter/extract_people.py
> +        tmp_faces = {}  # bboxes by ids
Нельзя пояснить, что это за такие временные лица? Почему некоторые рамки становятся временными? Лучше придумать более содержательное название.

2017-01-29 13:14 UTC, romovpa commented on boremeter/extract_people.py
>          for cur_id in cur_faces:
```python 
for cur_id, cur_face in cur_faces.iteritems():
   ... # cur_faces[cur_id] -> cur_face
```

2017-01-29 13:14 UTC, romovpa commented on boremeter/extract_people.py
>                      if not found and are_close(prev_faces[prev_id], cur_faces[cur_id]):
```python
for prev_id, prev_face in prev_faces.iteritems(): 
    if not found and prev_face.close_to(cur_face):
```
eh?

2017-01-29 13:14 UTC, romovpa commented on boremeter/extract_people.py
> +                        faces_ids_to_delete.append(cur_id)
**face**_ids_to_delete
просто английская грамматика

2017-01-29 13:14 UTC, romovpa commented on boremeter/gen_report.py
> +from util import temporary_directory
relative imports, ну емае

```python
from . import extract_people
from . import recognize_people
from .visualize import visualize
from .util import temporary_directory
```

писал же про это развернутый комментарий

2017-01-29 13:14 UTC, romovpa commented on boremeter/gen_report.py
> +def gen_html(filename, men_pc, ages, time_arr, attention_arr):
Может подавать этой функции на вход pandas.DataFrame с определенным набором колонок? Все массивы времени, внимание и др. будут заключены в один объект. И легко будет добавлять новые колонки — не нужно будет менять сигнатуру функции.

2017-01-29 13:14 UTC, romovpa commented on boremeter/gen_report.py
> +                                                              recognition_step=RECOGNITION_STEP,)
Мне больше нравится такая нотация:
```python
        detected_faces_df = recognize_people.recognize_people(
            tmp_dir=tmp_dir,
            frames_limit=args.frames_limit,
            caffe_models_path=caffe_models_path,
            recognition_step=RECOGNITION_STEP,
        )
```
Она позволяет не запариваться и не сокращать длину аргументов, из-за того что видите ли присваивание занимает много места. И нету такого огромного пустрого пространства на мониторе слева от аргументов.

Но т.к. в сообществе приняты и распространены оба варианта, не навязываю.

2017-01-29 13:14 UTC, romovpa commented on boremeter/recognize_people.py
> +    cc = cv2.CascadeClassifier(DETECTOR_CONFIG['VJ_cascade_path'])
Почему бы не назвать это как-нибудь `detector_clf`?
То что он каскадный, никак не влияет на его дальнейшее использование. А вот то что это классификатор, и он нужен для детекции лиц — хорошо бы подчеркнуть. Аббреввиатура `cc` такой информации точно не сообщает.

2017-01-29 13:14 UTC, romovpa commented on boremeter/recognize_people.py
>      for i in tqdm(detected_faces.index):
```python
for i, face_row in tqdm(detected_faces.iterrows()):
   ... make_image_name(face_row['frame'], face_row['person_id'])
```

2017-01-29 13:14 UTC, romovpa commented on boremeter/templates/report.html
>      time_row = document.getElementById('time_row');
row — это совсем не то слово
То что мы в русском называем временным рядом, то в английском time series.
time row звучит странно, а гуглится в первую очередь [вот это](https://en.wikipedia.org/wiki/Death_row)

2017-01-29 13:14 UTC, romovpa commented on boremeter/util.py
> +        shutil.rmtree(d)
No newline at end of file

2017-01-29 13:14 UTC, romovpa commented on boremeter/extract_people.py
> +        if not not_end:
"if not not end" , заикательный код
Предлагаю not_end -> has_more_frames

2017-01-29 13:17 UTC, iluhandric commented on boremeter/detector.py
>  def detect_faces(img, raw_detector='VJ'):
можно поднимать NotImplementedError(), если не VJ?

2017-01-31 22:01 UTC, romovpa requested changes

2017-01-31 22:01 UTC, romovpa commented on boremeter/recognize_people.py
`except` без типа исключения быть не должно, всегда указывай какие исключения обрабатываешь.

Банальный пример, почему плохо не указывать исключения:
Если цикл долгий, то ты не сможешь его прекратить по Ctrl+C, поскольку это будет вызывать KeyboardInterruptException, а у тебя глобальный обработчик запишет в возраст None и все. В результате терминал будет подвешен.

2017-01-31 22:01 UTC, romovpa commented on boremeter/visualize.py
>      except:
`exсept` без указания исключения

2017-01-31 22:01 UTC, romovpa commented on boremeter/visualize.py
> +    except:
except без исключения

2017-01-31 22:01 UTC, romovpa commented on boremeter/visualize.py
> +                                       people_df[people_df['frame'] == detection_step *
Вот этот аргумент лучше сначала посчитать и занести переменную с понятным названием, а потом передать функции. Иначе непонятно что ты передаешь вторым аргументом, какое-то адовое выражение.

2017-02-01 15:25 UTC, romovpa requested changes
Кажется, большую часть косяков я уже комментировал.

2017-02-01 15:25 UTC, romovpa commented on boremeter/bounding_boxes.py
> +        new_x = max(new_x, 0)
Это на грани наебательства. Сначала ты пишешь `new_x = 1`, а потом `new_x = 2`. В итоге разработчику придется распутать эту цепочку перезатираний значения переменной. 
Можно же просто:
```python
new_x = max(0, self.x - int(self.w * (scale - 1) / 2))
```

2017-02-01 15:25 UTC, romovpa commented on boremeter/bounding_boxes.py
> +        new_x = max(new_x, 0)
или вообще

```python
return BoundingBox(
    x=max(0, self.x - int(self.w * (scale - 1) / 2)),
    y=...,
)
```
(обязательно указывая имена аргументов, чтобы было понятно, что за выражение считается)

2017-02-01 15:25 UTC, romovpa commented on boremeter/bounding_boxes.py
> +        return BoundingBox(self.x, self.y, self.w, self.h)
Зачем это здесь? Чтобы ручки шаловливые могли написать говнокод?

2017-02-01 15:25 UTC, romovpa commented on boremeter/bounding_boxes.py
> +    return overlap_area
какой смысл строчек-пробелов в этой функции?

2017-02-01 15:25 UTC, romovpa commented on boremeter/bounding_boxes.py
> +    x = min(pts[0][0], pts[1][0], pts[2][0], pts[3][0])
какой смысл строчек-пробелов до и после docstring?

2017-02-01 15:25 UTC, romovpa commented on boremeter/detector.py
> +    raise NotImplementedError()
Оставь здесь `# TODO: implement <описание функции>` комментарий, как я просил ранее, для того чтобы было понятно, что здесь нужно реализовать и зачем ты оставил эту функцию.

2017-02-01 15:25 UTC, romovpa commented on boremeter/detector.py
> +    raise NotImplementedError()
и здесь `# TODO`

2017-02-01 15:25 UTC, romovpa commented on boremeter/detector.py
>  def detect_faces(img, raw_detector='VJ'):
Если один из предусмотренных raw_detector-ов, который еще не реализован — то можно NotImplementedError. Если же пользователь передаст бред в поле raw_detector и получит ответ NotImplementedError, то это будет большое удивление, т.к. ожидается ошибка.

2017-02-01 15:25 UTC, romovpa commented on boremeter/extract_people.py
> +    faces_df = pd.DataFrame(columns=['frame', 'person_id', 'x', 'y', 'w', 'h'])
зачем здесь строка-пробел?

2017-02-01 15:25 UTC, romovpa commented on boremeter/gen_report.py
> +import recognize_people
да сколько раз говорить, что relative import!
```python
from . import extra_people
from . import recognize_people
```

2017-02-01 15:25 UTC, romovpa commented on boremeter/gen_report.py
> +    men_pc, ages, frames_nums, attention_values = recognize_people.get_stats(faces_df)
зачем здесь строка-пробел?

2017-02-01 15:25 UTC, romovpa commented on boremeter/gen_report.py
> +                                                                recognition_step=RECOGNITION_STEP,)
может все-таки аргументы на новой строке?
```python
recognized_faces_df = recognize_people.recognize_people(
	detected_faces=extracted_faces,
	tmp_dir=tmp_dir,
	frames_limit=args.frames_limit,
	caffe_models_path=caffe_models_path,
	recognition_step=RECOGNITION_STEP,
)
```

2017-02-01 15:25 UTC, romovpa commented on boremeter/gen_report.py
> +                                                                recognition_step=RECOGNITION_STEP,)
🙏

2017-02-01 15:25 UTC, romovpa commented on boremeter/gen_report.py
> +                                                                recognition_step=RECOGNITION_STEP,)
и в вызовах выше тоже

2017-02-01 15:25 UTC, romovpa commented on boremeter/gen_report.py
> +        print ('Extracting people.....')
Не то чтобы я против, но что означает эта последовательность точек?
Почему не просто `'Extracting people'`?

2017-02-01 15:25 UTC, romovpa commented on boremeter/gen_report.py
зачем эта строка-пробел?

2017-02-01 15:25 UTC, romovpa commented on boremeter/gen_report.py
> +        recognized_faces_df.to_csv(args.output_csv.name)
Кажется, можно передать файл-объект `recognized_faces_df.to_csv(args.output_csv)`

2017-02-01 15:25 UTC, romovpa commented on boremeter/gen_report.py
> +        gen_html(args.output_html.name, recognized_faces_df)
в `gen_html()` можно принимать в качестве аргумента не `filename`, а файл-объект, и тогда:

1. не обязательно будет два раза открывать файл
2. `gen_html(args.output_html, recognized_faces_df)`
3. можно будет записать этот html не только в файл, но и например в веб-сокет

2017-02-01 15:25 UTC, romovpa commented on boremeter/gen_report.py
> +                      detection_step=DETECTION_STEP)
Первым трем аргументам тоже не помешает имя, так ведь будет понятнее что ты передаешь и зачем. 

Ну и здесь тоже можно по строчке на аргумент.

2017-02-01 15:25 UTC, romovpa commented on boremeter/extract_people.py
> +                                       ignore_index=True,)
```python
face_row = {
	'frame': cur_frame_num,
	'person_id': person_id,
	'x': face.x,
	'y': face.y,
	'w': face.w,
	'h': face.h,
}
faces_df = faces_df.append(face_df, ignore_index=True)
```

Следует иметь в виду, использование здесь `pandas.DataFrame.append` может быть очень неэффективным, т.к. заново создается DataFrame на каждой итерации. Но преждевременно оптимизировать не стоит.

2017-02-01 15:25 UTC, romovpa commented on boremeter/extract_people.py
> +        old_bboxes_by_id = new_bboxes_by_id.copy()
зачем это, если у BoundingBox нет мутабельных методов?

2017-02-01 15:25 UTC, romovpa commented on boremeter/recognize_people.py
> +        return self.net.predict([x], oversample=False)
А почему бы не передавать в `predict` сразу много заранее подготовленных изображений?
Это случаем не причина того, что у вас дофига долго работает распознавание лиц?

В сетки лучше заранее зарядить и прогнать сразу батч из изображений, т.к. операции переноса между оперативной памятью и памятью гпу, тензорные операции на гпу слабо зависят от размера данных, но занимают значительное время => нужно минимизировать число переносов между рам и гпу, минимизировать число тензорных операций.

2017-02-01 15:25 UTC, romovpa commented on boremeter/recognize_people.py
> +                                    )
Аргументы на новой строке с нормальным отступом?

2017-02-01 15:25 UTC, romovpa commented on boremeter/recognize_people.py
> +                                                                           detected_faces['person_id'][i])))
я уже комментировал подобную лапшу

2017-02-01 15:25 UTC, romovpa commented on boremeter/recognize_people.py
>      for i in tqdm(detected_faces.index):
я уже писал, что здесь правильно сделать
```python
for i, face_row in tqdm(detected_faces.iterrows()):
   ...
```
и не писать везде эти конченные индексы `[i]`

2017-02-01 15:25 UTC, romovpa commented on boremeter/recognize_people.py
> +    for i in detected_faces.index:
И здесь тоже `iterrows()`

2017-02-01 15:25 UTC, romovpa commented on boremeter/recognize_people.py
> +                                                                           detected_faces['person_id'][i])))
и эту лапшу нужно сделать по нормальному

2017-02-01 15:25 UTC, romovpa commented on boremeter/recognize_people.py
> +                                              genders[detected_faces['person_id'][i]][1] > 0.5 else 'Female'
И я уже писал про бэкслешы, ну епта

2017-02-01 15:25 UTC, romovpa commented on boremeter/recognize_people.py
>      for i in tqdm(detected_faces.index):
и `iterrows()`

2017-02-01 15:25 UTC, romovpa commented on boremeter/recognize_people.py
>      detected_faces = detected_faces.fillna(np.nan)
Ты здесь написал что-то вроде:
```python
x = None if x is None else x
```

2017-02-01 15:25 UTC, romovpa commented on boremeter/visualize.py
> +                                       people_df[people_df['frame'] == last_detection_frame_num]))
Непонятная лапша из аргументов

2017-02-01 15:25 UTC, romovpa commented on boremeter/extract_people.py
> +                new_bboxes_by_id[old_id] = old_bboxes_by_id[old_id].copy()
Зачем?

2017-02-05 14:55 UTC, iluhandric commented on boremeter/recognize_people.py
> +        return self.net.predict([x], oversample=False)
для этого надо прям конкретно так переписать все распознавание

2017-02-05 15:06 UTC, iluhandric commented on boremeter/recognize_people.py
>      detected_faces = detected_faces.fillna(np.nan)
туда может попасть лишний шум и распознаться, например, нос. Дальше обрабатывать такое не очень удобно.

2017-02-05 15:09 UTC, iluhandric commented on boremeter/recognize_people.py
> +        return self.net.predict([x], oversample=False)
https://trello.com/c/WD5rv6Ti/27--

2017-02-05 18:42 UTC, romovpa commented on boremeter/recognize_people.py
>      detected_faces = detected_faces.fillna(np.nan)
Нет, ты не понял. `fillna` заменяет `np.nan` на определенное значение, которое ты передаешь первым аргументом. Получается, что ты заменяешь `np.nan` на `np.nan` в таблице.

2017-02-05 18:49 UTC, romovpa requested changes
Еще чуть-чуть

2017-02-05 18:49 UTC, romovpa commented on boremeter/__init__.py
> +from recognize_people import recognize_faces
relative import

2017-02-05 18:49 UTC, romovpa commented on boremeter/detector.py
> +    raise RuntimeError('Detection method %s is not supported' % raw_detector)
Здесь лучше сделать цепочку из `if ... elif ... elif ... else`. Так во-первых понятно что есть альтернативы и выбирается только одна, а во вторых позволяет избежать ошибок по невнимательности, когда отрабатывают куски кода для сразу нескольких `raw_detector`-ов.

2017-02-06 14:34 UTC, romovpa approved these changes

2017-02-06 14:34 UTC, merged