Add switch for gpu mode in caffe, docker with gpu support
walterdd/Auditory_tracking pull request #9
Opened 2017-02-13 17:13 UTC by walterdd

- добавлен docker file с cuda и поддержкой gpu
- в main устанавливается caffe mode
- добавлен progress bar в extract people

2017-02-18 09:57 UTC, romovpa requested changes

2017-02-18 09:57 UTC, romovpa commented on boremeter/extract_people.py
> +	if not  has_more_frames:
тут после `not` зачем-то два пробела

2017-02-18 09:57 UTC, romovpa commented on docker/gpu/Dockerfile
> +FROM boremeter/caffe-opencv-cuda8.0
Отдельные каталоги для докерфайла делаются когда процесс сборки докер-контейнера нуждается в дополнительных файлах, не связанных непосредственно с проектом. Например, сложный bash-скрипт, который делает раскладку конфигов по нужным каталогам. У вас здесь вроде такого нет. Имеет смысл просто сделать в корне репозитория два докерфайла:

- `Dockerfile` (cpu, по-умолчанию)
- `Dockerfile.cuda` (с поддержкой куды)

[stackoverflow](http://stackoverflow.com/questions/27409761/multiple-dockerfiles-in-project)

2017-02-18 09:57 UTC, romovpa commented on docker/gpu/Dockerfile
> +FROM boremeter/caffe-opencv-cuda8.0
Ну и на самом деле я не очень понимаю, есть ли смысл делать два контейнера? Разве тот контейнер, который с поддержкой cuda не умеет работать в режиме CPU? Если так, то может просто его и оставить?

2017-02-18 18:27 UTC, walterdd commented on docker/gpu/Dockerfile
> +FROM boremeter/caffe-opencv-cuda8.0
Контейнер с поддержкой cuda весит еще на 4gb больше - всего 11gb, поэтому я думала оставить оба.

2017-02-21 09:12 UTC, romovpa approved these changes
👍

2017-02-21 09:56 UTC, merged